version: '3.8'

services:
  photo-editor:
    build: .
    container_name: phototune-app
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - photo-editor-data:/app/data

volumes:
  photo-editor-data:
